// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG35268KWqttcQdB698r1URLjUBvuUlgc',
    appId: '1:672845889731:web:213c2ce5ba6df1fc332276',
    messagingSenderId: '672845889731',
    projectId: 'dapursarjana-7fc76',
    authDomain: 'dapursarjana-7fc76.firebaseapp.com',
    storageBucket: 'dapursarjana-7fc76.appspot.com',
    measurementId: 'G-2CZLL2YXVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlXaWetVQ9ID2xzrXAuh9CR7iAAYlBEE',
    appId: '1:672845889731:android:40212f3312392ddc332276',
    messagingSenderId: '672845889731',
    projectId: 'dapursarjana-7fc76',
    storageBucket: 'dapursarjana-7fc76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPyzM4aGGxiw1hi0wqZ_qQBE3lHKunvU',
    appId: '1:672845889731:ios:35e7932d6c359799332276',
    messagingSenderId: '672845889731',
    projectId: 'dapursarjana-7fc76',
    storageBucket: 'dapursarjana-7fc76.appspot.com',
    iosBundleId: 'id.co.yasareksawiyata.dapursarjana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALPyzM4aGGxiw1hi0wqZ_qQBE3lHKunvU',
    appId: '1:672845889731:ios:17c729fdfe495684332276',
    messagingSenderId: '672845889731',
    projectId: 'dapursarjana-7fc76',
    storageBucket: 'dapursarjana-7fc76.appspot.com',
    iosBundleId: 'id.co.yasareksawiyata.dapursarjana.RunnerTests',
  );
}
